theme: jekyll-theme-simplex
logo_img: /assets/title_logo.svg
title: Ole370's Projects
email: 370.Ole@proton.me
description: >- # this means to ignore newlines until "baseurl:"
  A list of my past projects...
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_username: speedynurbesser
copyright: © Ole370 2024 <span class="divider">·</span> Icons from <a href="https://fontawesome.com/">FontAwesome</a>

collections:
    category:
        output: true
    authors:
        output: false

defaults:
  -
    scope:
      path: ""
      type: category
    values:
      layout: "category"